# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Pack / Publish on Github

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

env:
    DOTNET_VERSION: 7.0.x

jobs:
  Pack:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Add Nuget Source
      run: dotnet nuget add source --username cschuchardt88 --password ${{ secrets.NUGET_API_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/cschuchardt88/index.json"
    - name: Dotnet Pack Packages
      run: dotnet pack -c Release -o .
    - name: Dotnet Publish NeoEvents.SmartContract.Templates Package
      run: dotnet nuget push "NeoEvents.SmartContract.Templates.${VERSION}.nupkg" --api-key ${{ secrets.NUGET_API_TOKEN }} --source "github"
